# Generated by Django 2.2 on 2019-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('execution_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
