# Generated by Django 2.2 on 2019-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190906_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Полное описание'),
        ),
    ]
